networks:
  trans:
    name: trans

services:
  django:
    build: ./backend
    container_name: django
    depends_on:
      - db
    env_file: .env
    networks:
      - trans
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend

  db:
    build: ./database
    container_name: db
    env_file: .env
    networks:
      - trans
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data:
    name: pg-data