networks:
  trans:
    name: trans

services:
  django:
    build: ./backend
    container_name: django
    env_file: .env
    networks:
      - trans
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    depends_on:
      db:
        condition: service_healthy

  db:
    build: ./database
    container_name: db
    env_file: .env
    networks:
      - trans
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 5s
      timeout: 5s
      retries: 4

volumes:
  pg-data:
    name: pg-data