global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'django'
    metrics_path: /metrics
    static_configs:
      - targets: ['172.17.0.1:8000']
        labels:
          group: 'django-app'