# Generated by Django 5.0.6 on 2024-06-14 12:24

import authn.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authn', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', authn.models.CustomUserManager()),
            ],
        ),
    ]
